### ISSUE TITLE
"Wanted v8.5.0 but was v8.5.0"

### ISSUE THREAD

**Issue by robatron** [gobold/node-version-checker#5]
Hi there,

I'm getting the following error when `engines` specifies `v8.5.0` and running node `v8.5.0`:

> Error: Current node version does not match the engines section of the package.json. Wanted v8.5.0 but was v8.5.0. 

Here's my `engines` entry in my `package.json`:

```
{ ... "engines" : { "node" : "v8.5.0" } ... }
```

I've tried several other values and get similar errors:

- `"engines" : { "node" : "8.5.0" }` --> `Wanted 8.5.0 but was v8.5.0`
- `"engines" : { "node" : ">=8.5.0" }` --> `Wanted >=8.5.0 but was v8.5.0`

**Comment by Ellisande** [comment]
Hi @robatron I've tried to replicate this using node 8.5.0 and I am not seeing the same behavior.

package JSON:
```
  "engines": {
    "node": "8.5.0"
  },
```
Nvc result:
```
~/source/node-version-checker (master)$ node -v
v8.5.0
~/source/node-version-checker (master)$ node ./bin/nvc
info: Node version matches the engine version
```

Are you using the command line, or are you using it programmatically?

**Comment by robatron** [comment]
Ah, I forgot to mention, I was using the `checker` function from the API, not the `nvc` binary

**Comment by Ellisande** [comment]
Checker seems to be working for me as well. Here is the test that I tried:
```js
import {
  expect
}
from 'chai';
import {
  exec
}
from 'shelljs';
import fs from 'fs';
const checker = require('../dist/checker').default;

describe.only('8.5.0 issue', () => {
  const writeFile = (packageInfo) => fs.writeFileSync('package.json', JSON.stringify(packageInfo));

  before(() => exec('n 8.5.0'));
  it('correctly verifies v8.5.0', () => {
    var packageInfo = {
      engines: {
        node: '8.5.0'
      }
    };
    writeFile(packageInfo);
    try {
      checker();
    } catch (err) {
      expect(err).not.to.exist;
    }
  });
});
```

Test result:
```
~/source/node-version-checker (master)$ gulp test
[12:51:57] Using gulpfile ~/source/node-version-checker/gulpfile.js
[12:51:57] Starting 'clean'...
[12:51:57] Starting 'lint'...
[12:51:57] Finished 'clean' after 41 ms
[12:51:58] Finished 'lint' after 450 ms
[12:51:58] Starting 'build'...
[12:51:58] Finished 'build' after 146 ms
[12:51:58] Starting 'test'...


  8.5.0 issue
    ✓ correctly verifies v8.5.0


  1 passing (151ms)

[12:51:58] Finished 'test' after 293 ms
```

**Comment by robatron** [comment]
Hmm, you know what, I tried again with both the binary and the API, and both are working for me now. I'm not sure what happened. Thanks anyway!
